<?php

namespace App\Services\Smart;

use App\Models\Device;
use App\Models\Inventory;
use Illuminate\Support\Str;

class ConfigGeneratorService
{
    public function generateCiscoConfig(Device $device, ?Inventory $inventory, array $variables = []): string
    {
        $playbook = $variables['playbook_name'] ?? 'deployment.yml';
        $config = [];

        $config[] = '!';
        $config[] = '! Cisco Configuration Generated by AutoConfigLab';
        $config[] = '! Device: ' . ($device->hostname ?? 'Unknown');
        $config[] = '! Playbook: ' . $playbook;
        $config[] = '! Generated: ' . now()->toIso8601String();
        $config[] = '!';

        if (! empty($variables['hostname'])) {
            $config[] = 'hostname ' . $variables['hostname'];
            $config[] = '!';
        }

        if (! empty($variables['vlan_id'])) {
            $config = array_merge($config, $this->generateVlanConfig($variables));
        }

        if (! empty($variables['interface_name'])) {
            $config = array_merge($config, $this->generateInterfaceConfig($variables));
        }

        if (! empty($variables['routing_protocol'])) {
            $config = array_merge($config, $this->generateRoutingConfig($variables));
        }

        if (! empty($variables['dhcp_pool'])) {
            $config = array_merge($config, $this->generateDhcpConfig($variables));
        }

        if (! empty($variables['acl_rules'])) {
            $config = array_merge($config, $this->generateAclConfig($variables));
        }

        if (! empty($variables['snmp_community'])) {
            $config = array_merge($config, $this->generateSnmpConfig($variables));
        }

        $config[] = '!';
        $config[] = 'end';

        return implode("\n", $config);
    }

    private function generateVlanConfig(array $variables): array
    {
        $config = [];
        $vlanId = $variables['vlan_id'] ?? 1;
        $vlanName = $variables['vlan_name'] ?? 'VLAN' . $vlanId;

        $config[] = 'vlan ' . $vlanId;
        $config[] = ' name ' . $vlanName;
        $config[] = '!';

        return $config;
    }

    private function generateInterfaceConfig(array $variables): array
    {
        $config = [];
        $interfaceName = $variables['interface_name'] ?? 'GigabitEthernet0/1';
        $description = $variables['interface_description'] ?? 'Configured by AutoConfigLab';
        $vlan = $variables['access_vlan'] ?? null;
        $ipAddress = $variables['ip_address'] ?? null;
        $subnetMask = $variables['subnet_mask'] ?? '255.255.255.0';
        $mode = $variables['interface_mode'] ?? 'access';

        $config[] = 'interface ' . $interfaceName;
        $config[] = ' description ' . $description;

        if ($mode === 'trunk') {
            $config[] = ' switchport mode trunk';
            if (! empty($variables['allowed_vlans'])) {
                $config[] = ' switchport trunk allowed vlan ' . $variables['allowed_vlans'];
            }
            if (! empty($variables['native_vlan'])) {
                $config[] = ' switchport trunk native vlan ' . $variables['native_vlan'];
            }
        } else {
            $config[] = ' switchport mode access';
            if ($vlan) {
                $config[] = ' switchport access vlan ' . $vlan;
            }
        }

        if ($ipAddress) {
            $config[] = ' no switchport';
            $config[] = ' ip address ' . $ipAddress . ' ' . $subnetMask;
        }

        if (($variables['interface_shutdown'] ?? false) !== true) {
            $config[] = ' no shutdown';
        }

        $config[] = '!';

        return $config;
    }

    private function generateRoutingConfig(array $variables): array
    {
        $config = [];
        $protocol = $variables['routing_protocol'] ?? 'static';

        if ($protocol === 'static') {
            if (! empty($variables['static_route_network']) && ! empty($variables['static_route_next_hop'])) {
                $config[] = 'ip route ' . $variables['static_route_network'] . ' ' . $variables['static_route_mask'] . ' ' . $variables['static_route_next_hop'];
            }
        } elseif ($protocol === 'ospf') {
            $processId = $variables['ospf_process_id'] ?? 1;
            $config[] = 'router ospf ' . $processId;
            if (! empty($variables['ospf_network'])) {
                $config[] = ' network ' . $variables['ospf_network'] . ' ' . $variables['ospf_wildcard'] . ' area ' . ($variables['ospf_area'] ?? 0);
            }
            if (! empty($variables['ospf_passive_interface'])) {
                $config[] = ' passive-interface ' . $variables['ospf_passive_interface'];
            }
        } elseif ($protocol === 'eigrp') {
            $asn = $variables['eigrp_asn'] ?? 1;
            $config[] = 'router eigrp ' . $asn;
            if (! empty($variables['eigrp_network'])) {
                $config[] = ' network ' . $variables['eigrp_network'];
            }
        }

        $config[] = '!';

        return $config;
    }

    private function generateDhcpConfig(array $variables): array
    {
        $config = [];
        $poolName = $variables['dhcp_pool'];
        $network = $variables['dhcp_network'] ?? '192.168.10.0';
        $mask = $variables['dhcp_mask'] ?? '255.255.255.0';
        $defaultRouter = $variables['dhcp_default_router'] ?? '';
        $dnsServer = $variables['dhcp_dns_server'] ?? '';
        $start = $variables['dhcp_start'] ?? '100';
        $end = $variables['dhcp_end'] ?? '200';

        $config[] = 'ip dhcp pool ' . $poolName;
        $config[] = ' network ' . $network . ' ' . $mask;
        if ($defaultRouter) {
            $config[] = ' default-router ' . $defaultRouter;
        }
        if ($dnsServer) {
            $config[] = ' dns-server ' . $dnsServer;
        }
        $config[] = '!';

        $config[] = 'ip dhcp excluded-address ' . $network . ' ' . substr($network, 0, strrpos($network, '.')) . '.1';
        $config[] = 'ip dhcp excluded-address ' . $network . ' ' . substr($network, 0, strrpos($network, '.')) . '.' . ($start - 1);
        $config[] = '!';

        return $config;
    }

    private function generateAclConfig(array $variables): array
    {
        $config = [];
        $rules = $variables['acl_rules'] ?? [];
        $aclNumber = $variables['acl_number'] ?? 100;

        if (empty($rules)) {
            return $config;
        }

        $config[] = 'ip access-list extended ACL-' . $aclNumber;

        foreach ($rules as $rule) {
            $action = $rule['action'] ?? 'permit';
            $protocol = $rule['protocol'] ?? 'ip';
            $source = $rule['source'] ?? 'any';
            $destination = $rule['destination'] ?? 'any';
            $port = $rule['port'] ?? '';

            $ruleText = $action . ' ' . $protocol . ' ' . $source;
            if ($port) {
                $ruleText .= ' eq ' . $port;
            }
            $ruleText .= ' ' . $destination;

            $config[] = $ruleText;
        }

        $config[] = '!';

        return $config;
    }

    private function generateSnmpConfig(array $variables): array
    {
        $config = [];

        $community = $variables['snmp_community'] ?? 'public';
        $location = $variables['snmp_location'] ?? 'AutoConfigLab';
        $contact = $variables['snmp_contact'] ?? 'admin@example.com';

        $config[] = 'snmp-server community ' . $community . ' ro';
        $config[] = 'snmp-server location ' . $location;
        $config[] = 'snmp-server contact ' . $contact;
        $config[] = '!';

        return $config;
    }

    public function generateMultiDeviceConfig(array $devices): array
    {
        $configs = [];

        foreach ($devices as $deviceData) {
            $device = $deviceData['device'] ?? null;
            $inventory = $deviceData['inventory'] ?? null;
            $variables = $deviceData['variables'] ?? [];

            if ($device) {
                $configs[$device->hostname ?? 'unknown'] = $this->generateCiscoConfig($device, $inventory, $variables);
            }
        }

        return $configs;
    }

    public function presetScenarios(): array
    {
        return [
            'success' => [
                'key' => 'success',
                'label' => 'Success Scenario',
                'description' => 'Normal deployment that completes successfully',
                'expected_status' => 'completed',
            ],
            'validation_failure' => [
                'key' => 'validation_failure',
                'label' => 'Validation Failure',
                'description' => 'Deployment blocked by validation checks',
                'expected_status' => 'validation_failed',
            ],
            'connection_failure' => [
                'key' => 'connection_failure',
                'label' => 'Connection Failure',
                'description' => 'Cannot connect to device',
                'expected_status' => 'failed',
            ],
            'config_failure' => [
                'key' => 'config_failure',
                'label' => 'Configuration Failure',
                'description' => 'Configuration rejected by device',
                'expected_status' => 'failed',
            ],
            'dhcp_dns_http_lab' => [
                'key' => 'dhcp_dns_http_lab',
                'label' => 'DHCP/DNS/HTTP Lab',
                'description' => 'Lab with DHCP, DNS, and HTTP services',
                'expected_status' => 'completed',
            ],
            'ospf_md5_lab' => [
                'key' => 'ospf_md5_lab',
                'label' => 'OSPF MD5 Lab',
                'description' => 'Lab with OSPF routing and MD5 authentication',
                'expected_status' => 'completed',
            ],
            'router_static_lab' => [
                'key' => 'router_static_lab',
                'label' => 'Router Static Lab',
                'description' => 'Lab with static routing configuration',
                'expected_status' => 'completed',
            ],
        ];
    }

    public function suggestForDevice(Device $device): array
    {
        $hostname = $device->hostname ?? 'UNKNOWN';
        $platform = strtolower($device->platform ?? '');
        $vendor = strtolower($device->vendor ?? '');
        $mgmtIp = $device->mgmt_ip ?? '';
        $inventory = $device->inventory;

        $missingHints = [];

        if (empty($device->hostname)) {
            $missingHints[] = 'Missing hostname';
        }
        if (empty($device->mgmt_ip)) {
            $missingHints[] = 'Missing management IP';
        }
        if (empty($device->platform)) {
            $missingHints[] = 'Missing platform';
        }
        if (empty($device->auth_username)) {
            $missingHints[] = 'Missing authentication username';
        }

        $deviceProfile = 'GENERIC';
        if (str_contains($platform, 'switch') || str_contains($platform, 'catalyst')) {
            $deviceProfile = 'SWITCH';
        } elseif (str_contains($platform, 'router') || str_contains($platform, 'isr')) {
            $deviceProfile = 'ROUTER';
        } elseif (str_contains($platform, 'firewall') || str_contains($platform, 'asa')) {
            $deviceProfile = 'FIREWALL';
        }

        $routingProtocol = 'none';
        if ($deviceProfile === 'ROUTER') {
            $routingProtocol = 'ospf';
            if ($inventory && str_contains(strtolower($inventory->name ?? ''), 'enterprise')) {
                $routingProtocol = 'eigrp';
            }
        }

        $vlanId = 10;
        if ($deviceProfile === 'SWITCH') {
            $vlanId = match (true) {
                str_contains($hostname, 'access') => 20,
                str_contains($hostname, 'mgmt') => 99,
                str_contains($hostname, 'voice') => 30,
                default => 10,
            };
        }

        $ipRange = '192.168.10.0/24';
        if (! empty($mgmtIp)) {
            $parts = explode('.', $mgmtIp);
            if (count($parts) === 4) {
                $thirdOctet = (int) $parts[2];
                $thirdOctet = ($thirdOctet + 10) % 254;
                $ipRange = "192.168.{$thirdOctet}.0/24";
            }
        }

        $inventoryName = $inventory?->name ?? 'default';
        if (str_contains($inventoryName, 'datacenter')) {
            $ipRange = '10.0.10.0/24';
            if ($deviceProfile === 'ROUTER') {
                $routingProtocol = 'bgp';
            }
        }

        return [
            'device_profile' => $deviceProfile,
            'recommended_routing_protocol' => $routingProtocol,
            'suggested_vlan_id' => $vlanId,
            'suggested_ip_range' => $ipRange,
            'missing_hints' => $missingHints,
            'device_info' => [
                'hostname' => $hostname,
                'platform' => $device->platform ?? 'Unknown',
                'vendor' => $device->vendor ?? 'Unknown',
                'mgmt_ip' => $mgmtIp,
                'inventory' => $inventoryName,
                'connection' => $device->connection ?? 'network_cli',
                'status' => $device->status ?? 'unknown',
            ],
        ];
    }
}