apiVersion: v1
kind: ConfigMap
metadata:
  name: dlds-logstash-pipeline
  namespace: dlds-soc
data:
  dlds-pipeline.conf: |
    input {
      kafka {
        bootstrap_servers => "kafka-1.kafka.svc.cluster.local:9092,kafka-2.kafka.svc.cluster.local:9092,kafka-3.kafka.svc.cluster.local:9092"
        topics => ["dlds.raw.telemetry"]
        group_id => "cg-logstash-indexer"
        auto_offset_reset => "earliest"
        codec => json
      }
    }

    filter {
      if [timestamp] {
        date {
          match => [ "timestamp", "UNIX", "ISO8601" ]
          target => "@timestamp"
        }
      }
      mutate {
        convert => {
          "bytes_sent" => "integer"
          "duration" => "float"
          "severity" => "integer"
          "ml_confidence" => "float"
          "src_port" => "integer"
          "dst_port" => "integer"
        }
      }
      if ![event_id] or [event_id] == "" {
        fingerprint {
          source => [
            "timestamp",
            "sensor",
            "src_ip",
            "src_port",
            "dst_ip",
            "dst_port",
            "protocol",
            "alert_signature",
            "bytes_sent"
          ]
          method => "SHA256"
          target => "event_id"
          concatenate_sources => true
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "dlds-events-%{+YYYY.MM.dd}"
        document_id => "%{event_id}"
        manage_template => false
      }
      stdout { codec => rubydebug }
    }
