apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlds-chaos-runner
  namespace: dlds-soc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dlds-chaos-role
  namespace: dlds-soc
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dlds-chaos-rolebinding
  namespace: dlds-soc
subjects:
  - kind: ServiceAccount
    name: dlds-chaos-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dlds-chaos-role
