<?php

namespace App\Services\Topology;

use App\Models\GeneratedConfig;
use App\Models\Topology;
use App\Models\TopologyDevice;
use Illuminate\Support\Facades\DB;

class TopologyConfigGeneratorService
{
    public function __construct(
        private readonly CiscoRouterConfigService $routerConfigService,
        private readonly CiscoSwitchConfigService $switchConfigService,
        private readonly CiscoValidationService $validationService
    ) {}

    /**
     * @return array{generated:array<int, GeneratedConfig>, errors:array<int, string>, warnings:array<int, string>}
     */
    public function generateForTopology(Topology $topology): array
    {
        $topology->loadMissing([
            'topologyDevices.interfaces',
            'topologyLinks',
        ]);

        $validation = $this->validationService->validateTopology($topology);
        if ($validation['errors'] !== []) {
            return [
                'generated' => [],
                'errors' => $validation['errors'],
                'warnings' => $validation['warnings'],
            ];
        }

        $generatedConfigs = DB::transaction(function () use ($topology): array {
            $saved = [];

            /** @var TopologyDevice $device */
            foreach ($topology->topologyDevices as $device) {
                $configText = $this->renderByDeviceType($device);

                $saved[] = GeneratedConfig::updateOrCreate(
                    [
                        'topology_id' => $topology->id,
                        'topology_device_id' => $device->id,
                    ],
                    [
                        'config_text' => $configText,
                        'config_hash' => hash('sha256', $configText),
                        'validation_errors' => [],
                        'generated_at' => now(),
                    ]
                );
            }

            return $saved;
        });

        return [
            'generated' => $generatedConfigs,
            'errors' => [],
            'warnings' => $validation['warnings'],
        ];
    }

    private function renderByDeviceType(TopologyDevice $device): string
    {
        $interfaces = $device->interfaces()->orderBy('name')->get();
        $type = strtolower($device->device_type);

        if ($type === 'switch') {
            return $this->switchConfigService->generateSwitchConfig($device, $interfaces);
        }

        // Router and multilayer switches are generated by L3 service.
        return $this->routerConfigService->generateRouterConfig($device, $interfaces);
    }
}
