apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dlds-soc
resources:
  - namespace.yaml
  - configmap-dlds-env.yaml
  - configmap-filebeat-sidecar.yaml
  - configmap-logstash.yaml
  - configmap-logstash-pipeline.yaml
  - secret-laravel-api.example.yaml
  - deployment-logstash.yaml
  - service-logstash.yaml
  - deployment-pipeline.yaml
  - hpa-pipeline.yaml
  - pvc-ops-data.yaml
  - cronjob-drift-monitor.yaml
  - rbac-chaos.yaml
  - cronjob-chaos-drill.yaml
